name: gtk-bh-ai-7-8
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.13
  - tensorflow
  - keras
  - pytorch
  - pandas
  - jupyter
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - pip
  - ipywidgets
  - ipykernel
  - pillow
  - pydotplus
  - pip:
      - adversarial-robustness-toolbox

  